{% set name = "snowflake" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c93154af83b52f7166659a3a38f046e3a6d781ddbb86765045d399e7eadb32a9
  patches:
    # update 1.3.0: patch still needed
    - patches/0001-fix-pyproject.patch

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  # snowflake_legacy requires py >=3.8,<3.12
  # https://inspector.pypi.io/project/snowflake-legacy/1.0.0/packages/94/41/a6211bd2109913eee1506d37865ab13cf9a8cc2faa41833da3d1ffec654b/snowflake_legacy-1.0.0.tar.gz/snowflake_legacy-1.0.0/pyproject.toml#line.8
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - snowflake.core =={{ version }}
    - snowflake_legacy
  run_constrained:
    - snowflake-ml-python ==1.8.1

test:
  imports:
    - snowflake
    - snowflake._legacy
    - snowflake.core
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/snowflake
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API
  description: |
    The Snowflake Python API is the unified Python API across
    all Snowflake workloads, providing APIs for all Snowflake
    resources across data engineering, Snowpark, Snowpark ML,
    and client application workloads.
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake

extra:
  recipe-maintainers:
    - lorepirri
