{% set name = "snowflake" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a8c0fb1ac1a2720a0c913c3c1cd9151267f9d3c4373d2d2055a93281ec5ca28
  patches:
    # update 0.10.0: patch still needed
    - patches/0001-fix-pyproject.patch

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  # snowflake.core not available for s390x
  skip: true  # [py<38 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - snowflake.core =={{ version }}
    - snowflake_legacy
test:
  imports:
    - snowflake
    - snowflake._legacy
    - snowflake.core
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/snowflake
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API
  description: |
    The Snowflake Python API is the unified Python API across
    all Snowflake workloads, providing APIs for all Snowflake
    resources across data engineering, Snowpark, Snowpark ML,
    and client application workloads.
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake

extra:
  recipe-maintainers:
    - lorepirri
