{% set name = "snowflake" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92da55d574e0bfd3b83f27180a0d8f940d50a90ee22c12892023221ebb488701
  patches:
    # update 1.9.0: patch still needed
    - patches/0001-fix-pyproject.patch

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  skip: true  # [py<310 or py>313]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - snowflake.core =={{ version }}
    - snowflake_legacy

test:
  imports:
    - snowflake
    - snowflake._legacy
    - snowflake.core
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://pypi.org/project/snowflake
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API
  description: |
    The Snowflake Python API is the unified Python API across
    all Snowflake workloads, providing APIs for all Snowflake
    resources across data engineering, Snowpark, Snowpark ML,
    and client application workloads.
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake

extra:
  recipe-maintainers:
    - lorepirri
