{% set name = "snowflake" %}
{% set version = "1.13.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59291b0a93f3b98ba1dc6a1153bfcab1f4ba75dbd84a3abcad391e5d38ddb1f4
  patches:
    # update 1.13.1: patch still needed
    - patches/0001-fix-pyproject.patch

build:
  # allows SF to rebuild the package as needed without incurring a
  # higher build number than the package we release
  number: 100
  skip: true  # [py<310 or py>314]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - snowflake.core =={{ version }}
    - snowflake_legacy
  run_constrained:
    # ml
    - snowflake-ml-python >=1.4.0

test:
  imports:
    - snowflake
    - snowflake._legacy
    - snowflake.core
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://pypi.org/project/snowflake
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Snowflake Python API
  description: |
    The Snowflake Python API is the unified Python API across
    all Snowflake workloads, providing APIs for all Snowflake
    resources across data engineering, Snowpark, Snowpark ML,
    and client application workloads.
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-python-api/snowflake-python-overview
  dev_url: https://pypi.org/project/snowflake

extra:
  recipe-maintainers:
    - lorepirri
